routes/web.php
	Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->withoutMiddleware(['completed']);

	Route::match(['get', 'post'], '/user/profile', 'UserController@profile')->name('user_profile')->withoutMiddleware(['completed']);

	Route::group(['middleware' => ['permission:manage sales']], function () {
		Route::resource('credit-notes', 'CreditNoteController');
		Route::get('credit-notes/{credit_note}/pdf', 'CreditNoteController@pdf')->name('credit-notes.pdf');
		Route::get('credit-notes/{credit_note}/print', 'CreditNoteController@print')->name('credit-notes.print');
		Route::post('credit-notes/{credit_note}/mail', 'CreditNoteController@mail')->name('credit-notes.mail');

		Route::resource('estimates', 'EstimateController');
		/* Route::resource('remissions', 'RemissionController'); */
		Route::get('estimates/{estimate}/pdf', 'EstimateController@pdf')->name('estimates.pdf');
		Route::get('estimates/{estimate}/print', 'EstimateController@print')->name('estimates.print');
		Route::post('estimates/{estimate}/mail', 'EstimateController@mail')->name('estimates.mail');
		Route::prefix('pos')->group(function () {
			Route::get('/', 'PosController@index')->name('pos.index');
			Route::post('/order/create/{mode?}', 'PosController@createOrder')->where('mode', 'online|offline')->name('pos.createOrder');
		});
		Route::post('estimates/{estimate}/approve', 'EstimateController@getClone')->name('estimates.approve');
		Route::resource('remissions', 'RemissionController');
	});

	Route::group(['middleware' => ['permission:manage expenses']], function () {
		Route::resource('debit-notes', 'DebitNoteController');
		Route::resource('purchase-orders', 'PurchaseOrderController');
		Route::resource('ncfs', 'NcfController');
	});

	/* invoices and transaction related routes*/
	Route::group(['middleware' => ['redirect_for_invoices']], function () {
		Route::get('invoices', function() {
			return redirect()->route('invoices.index', ['type' => 'sale']);
		});
		Route::get('invoices/create/{type}', 'InvoiceController@create')->where('type', 'sale|recurring|supplier')->name('invoices.create');
		Route::post('invoices/{type}', 'InvoiceController@store')->where('type', 'sale|recurring|supplier')->name('invoices.store');
		Route::get('invoices/{type}', 'InvoiceController@index')->where('type', 'sale|recurring|supplier')->name('invoices.index');
		Route::post('invoices/{invoice}/void', 'InvoiceController@void')->name('invoices.void');

		Route::resource('invoices', 'InvoiceController')->except([
		    'create', 'store', 'index'
		]);

		Route::get('invoices/{invoice}/pdf', 'InvoiceController@pdf')->name('invoices.pdf');
		Route::get('invoices/{invoice}/print', 'InvoiceController@print')->name('invoices.print');
		Route::get('invoices/{invoice}/print/template/{template_no}/{view}', 'InvoiceController@printWithTemplate');
		Route::post('invoices/{invoice}/mail', 'InvoiceController@mail')->name('invoices.mail');
		Route::get('invoices/{invoice}/makeProduction', 'InvoiceController@makeProductionOrder')->name('invoices.makeProduction');
		Route::get('invoices/{invoice}/clone', 'InvoiceController@clone')->name('invoices.clone');
		Route::get('invoices/{invoice}/recurring', 'InvoiceController@recurring')->name('invoices.recurring');
		Route::post('invoices/{invoice}/makeRecurring', 'InvoiceController@convertInvoice')->name('invoices.makeRecurring');
		Route::resource('shipping', 'ShippingController');
	});
	Route::resource('restaurant-table', 'TableController');
	//Route::group(['middleware' => ['redirect_for_accountrecivable']], function () {
		Route::get('receivable','AccountReceivableController@index')->name('receivable.index');
		Route::get('receivable/create','AccountReceivableController@create')->name('receivable.create');
		Route::post('receivable','AccountReceivableController@store')->name('receivable.store');
		Route::get('delete/{id}','AccountReceivableController@destroy')->name('receivable.delete');
		Route::get('pdf/{id}','AccountReceivableController@downloadpdf')->name('receivable.pdf');
		Route::get('view/{id}','AccountReceivableController@show')->name('receivable.show');
		

		//});



	Route::group(['middleware' => ['redirect_for_transactions']], function () {
		Route::get('transactions', function() {
			return redirect()->route('transactions.index', ['type' => 'in']);
		});
		
		Route::get('transactions/{type}', 'TransactionController@index')->where('type', 'in|out|recurring')->name('transactions.index');
		Route::get('transactions/create/{type}', 'TransactionController@create')->where('type', 'in|out|recurring')->name('transactions.create');
		Route::post('transactions/{type}', 'TransactionController@store')->where('type', 'in|out|recurring')->name('transactions.store');

		Route::resource('transactions', 'TransactionController')->except([
		    'create', 'store', 'index'
		]);
		Route::get('transactions/{transaction}/print', 'TransactionController@print')->name('transactions.print');
	});

	Route::group(['middleware' => ['permission:manage contacts']], function () {
		Route::resource('clients', 'ClientController');
		Route::resource('suppliers', 'SupplierController');
	});
		
	Route::group(['middleware' => ['permission:manage inventories']], function () {
		Route::resource('taxes', 'TaxController')->except([
		    'show'
		]);
		Route::get('taxes/{tax}', function() {
			return redirect()->route('taxes.index');
		});
		Route::resource('item-categories', 'ItemCategoryController')->except([
		    'show'
		]);
		Route::get('item-categories/{item_category}', function() {
			return redirect()->route('item-categories.index');
		});
		Route::any('inventories/search', 'InventoryController@search')->name('inventories.search')->withoutMiddleware(['permission:manage inventories']);
		Route::resource('inventories', 'InventoryController');
		Route::resource('inventory-adjustments', 'InventoryAdjustmentController');
		Route::resource('units', 'UnitController');
	});

	Route::middleware([AdminOrSuperAdmin::class])->group(function () {
		Route::get('/settings/user', 'UserController@edit')->name('users.edit');
		Route::post('/settings/user', 'UserController@update')->name('users.update');
		Route::get('/settings/company', 'UserController@company')->name('company.edit');
		Route::post('/settings/company', 'UserController@companyUpdate')->name('company.update');
		Route::resource('employees', 'EmployeeController');
		Route::resource('departments', 'DepartmentController');
		Route::resource('designations', 'DesignationController');
		Route::resource('insurance-brands', 'InsuranceBrandController');
		Route::resource('leave-types', 'LeaveTypeController');
		Route::resource('leave-applications', 'LeaveApplicationController');
		Route::get('leave-reports', 'LeaveReportController@index')->name('leave-reports.index');
		Route::get('summary-report', 'LeaveReportController@summary')->name('summary-report.summary');
		Route::get('my-leave-report', 'LeaveReportController@my_leave_report')->name('my-leave-report.my-leave');
		Route::get('requested-applications', 'LeaveApplicationController@requested_applications')->name('requested-applications.requested');

		Route::resource('benefits', 'BenefitController');
		Route::resource('with-holdings', 'WithHoldingController');
		Route::resource('discounts', 'DiscountController');
		Route::resource('extra-hours', 'ExtraHourController');
		Route::resource('payroll-reports', 'PayrollReportController');

		Route::resource('roles', 'RoleController')->except([
		    'show'
		]);
		Route::get('roles/{role}', function() {
			return redirect()->route('roles.index');
		});

		Route::resource('memberships', 'MembershipController');

		/* Route::resource('leaves', 'LeaveController'); */

		Route::resource('leaves', 'LeaveController', ['parameters' => [
    		'leaves' => 'leave'
		]]);

		Route::post('/paid', 'PayrollReportController@paid')->name('employees.paid');
		Route::resource('history', 'HistoryController');
	});

	Route::prefix('user-management')->middleware([AdminOrSuperAdmin::class])->group(function () {
		 Route::get('users', 'UserManagementController@users')->name('user-management.users');
		Route::resource('users', 'UserManagementController')->except([
		    'index',
		    'show',
		])->names([
		    'create' => 'user-management.users.create',
		    'store' => 'user-management.users.store',
		    'edit' => 'user-management.users.edit',
		    'update' => 'user-management.users.update',
		    'destroy' => 'user-management.users.destroy'
		])->parameters([
		    'users' => 'company_user'
		]); 

		/*Route::resource('roles', 'RoleController')->except([
		    'show'
		])->names([
		    'index' => 'user-management.roles.create',
		    'create' => 'user-management.roles.create',
		    'store' => 'user-management.roles.store',
		    'edit' => 'user-management.roles.edit',
		    'update' => 'user-management.roles.update',
		    'destroy' => 'user-management.roles.destroy'
		]);*/
		

		// Route::get('roles', 'UserManagementController@roles')->name('user-management.roles');
		// Route::match(['get', 'post'], 'roles/create', 'UserManagementController@createRole')->name('user-management.roles.create');
		// Route::get('roles/{role}', 'UserManagementController@editRole')->name('user-management.roles.edit');
		// Route::put('roles/{role}/update', 'UserManagementController@assignPermissionsToRole')->name('user-management.roles.update');
	});

	Route::group(['middleware' => ['permission:manage inventories|manage contacts']], function () {
		Route::get('/import/{resource}', 'ImportController@showForm')->where('resource', 'clients|suppliers|inventories|item-categories|banks')->name('import_resource');
		Route::post('/import/{resource}', 'ImportController@processImport')->where('resource', 'clients|suppliers|inventories|item-categories|banks')->name('import_process');

		Route::get('/export/{resource}', 'ExportController@export')->where('resource', 'clients|suppliers|inventories|item-categories')->name('export_resource');

app/Shipping.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Shipping extends Model
{
    use SoftDeletes;

    protected $fillable = [
'user_id' , 'company_id', 'invoice_id' ,'shipping_cost','status'
    ];
    protected $table = 'shippings';

    public function company()
    {
        return $this->belongsTo('App\Company');
    }
    public function invoices()
    {
        return $this->belongsTo('App\invoice');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/ShippingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Invoice;
use App\User;
use App\Item;
use PDF;
use Cache;
class ShippingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $type = self::SALE)
    {
        $user = $request->user();
        $invoices = $user->company->invoices->where('shipping_cost', '!=', '0')->values();      
        if ($request->wantsJson() || $request->ajax()) {
            $jsonCollection = collect();
            $invoices->each(function ($item, $key) use ($jsonCollection) {

                $jsonCollection->push([
                    'id' => $item->id,
                    'contact' => $item->contact,
                    'start_date' => $item->start_date,
                    'expiration_date' => $item->expiration_date,
                    'internal_number' => $item->internal_number,
                    'notes' => $item->notes,
                    'calculation' => $item->calculation,

                ]);
            });
            return response()->json(['data' => $jsonCollection]);
        }
        return view('shipping.index', compact('invoices', 'type'));
    }
  
    public function show(Request $request, $invoices)
    {
        $user = $request->user();
        $invoices = Invoice::where('id' , $invoices)->get();
        if ($request->has('view')) 
        {
            $viewType = $request->input('view');
        } else
        {
            $viewType = 'view-order';
        }
        
        return view('shipping.show', compact('invoices', 'viewType'));
        
    }


}

resources/views/shipping/index.blade.php
@extends('layouts.dashboard')
@section('title', trans('labels.shipping'))
@section('content')
<div class="dashboard-right cust-dashboard-md-right">
 <div class="menu-icon">
  <i class="fa fa-bars" aria-hidden="true"></i>
 </div>
<div class="invoice-container">
    <h2>{{ __('labels.shipping') }}</h2>
    <div class="custom-tooltip"><span class="help-icon"><i class="fa fa-question-circle" aria-hidden="true"></i></span>
     <span class="tooltiptext">{{ __('labels.if_you_need_help_creating').' '.__('labels.invoice') }},</span>
    </div>
    <div class="tabs-custom">
    <div class="tab-content">
    <div class="tab-pane active">
    <div class="cal-filter-cnt cal-filter-cust-btns" id="dates-filters" style="display:none">
     <span>{{ __('labels.from') }}: <input name="date-filter-min" id="date-filter-min" type="text" autocomplete="off"></span>
     <span>{{ __('labels.to') }}: <input name="date-filter-max" id="date-filter-max" type="text" autocomplete="off"></span>
    </div>
    <div class="list-table-custom  products-table table-responsive">
    <table class="table table-striped" id="shipping-adjustments-list-table">
        <thead>
          <tr>
            <th>{{ __('labels.id') }}</th>
            <th>{{ __('labels.contact') }}</th>
            <th>{{ __('labels.creation_date') }}</th>
            <th>{{ __('labels.delivery_date') }}</th> 
            <th>{{ __('labels.invoice_number') }}</th> 
            <th>{{ __('labels.notes') }}</th>
            <th>{{ __('labels.status') }}</th>
            <th>{{ __('labels.actions') }}</th>
          </tr>
          </thead>
           <tbody>
            @foreach ($invoices as $invoice)
            <tr>
             <td>{{ $invoice->id }}</td>
             <td>{{ $invoice->contact->name }}</td>
             <td>{{ dateFormat($invoice->start_date) }}</td>
             <td>{{ dateFormat($invoice->expiration_date) }}</td>
             <td>{{ $invoice->internal_number }}</td>
             <td>{{ $invoice->notes }}</td>
             <td>{{ $invoice->calculation['status'] }}</td>
             <td class="to-show">
              <div class="inner-to-show">
               <i class="fa fa-sort-desc action-btn" class="dropdown-toggle"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
              <div class="dropdown-menu">
                <ul>
                 <li><a href="{{route('shipping.show', $invoice)}}">{{ __('labels.view') }}</a></li>
                </ul> 
              </div>
                 </div>
             </td>
            </tr>
            @endforeach
          </tbody>
          </table>
         </div>
        </div>
       </div>
    </div>
   </div>
  </div>
<div class="clearfix"></div>
@endsection

resources/views/shipping/show.blade.php
@extends('layouts.dashboard')
@section('title', trans('labels.show').' '.trans('labels.invoice'))
@section('content')
<input type="hidden" name="resource_type" value="">
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <a class="arrow-back d-block"href="{{ route('shipping.index') }}">{{ __('labels.back') }}</a>
          @foreach ($invoices as $invoice)
          <h2><b>{{ __('labels.invoice') }}  {{ $invoice->internal_number }}</b></h2>
          @endforeach
    </div>
        <div class="action-btns-view show-wrap-btns">
        <div class="show-wrap-btns-inner">
        <!-- <a class="btn-custom print-this-shipping" data-id="{{ $invoice->id }}" data-type="{{ $viewType }}"><i class="fa fa-print"></i> {{ __('labels.print') }}</a> -->
        <!-- <a role="button" data-toggle="modal" data-target="#ShippingEmailModal" href="javascript:void(0)" class="btn-custom"><i class="fa fa-envelope"></i> {{ __('labels.send_by_mail') }}</a>        -->
        <a href="#"class="btn-custom"><i class="fa fa-print"></i> </i> {{ __('labels.print') }}</a> 
        <a href="#" class="btn-custom" id="invoice-download-btn"><i class="fa fa-download"></i> {{ __('labels.download') }}</a>
        <a href="#" class="btn-custom"><i class="fa fa-envelope"></i> {{ __('labels.send_by_mail') }}</a>
        <a href="#" class="btn-custom" id="invoice-download-btn"> {{ __('labels.mark_as_shipped') }}</a>
    </div>
    </div>
        <div class="  products-table table-responsive">
         <div class="default-form view-form">
           <div class="generate-invoice">
            <div id="invoice-custom-wrap-block" class="view-form-custom custom-view-info-client">
             <table class="table class="cutom-td"">
             @foreach ($invoices as $invoice)
             <tr>
              <td class="cutom-td"><b>{{ __('labels.client') }}</b></td>
              <td>{{ $invoice->contact->name }}</td>
              <td><b>{{ __('labels.creation_date') }}</b></td>
              <td>{{ dateFormat($invoice->start_date) }}</td>
             </tr>
             <tr>
              @if($viewType != 'production-order')
              <td><b>{{ __('labels.tax_id') }}</b></td>
              <td>{{ $invoice->contact->tax_id }}</td>
              @endif
              <td><b>{{ __('labels.expiration_date') }}</b></td>
              <td>{{ dateFormat($invoice->expiration_date) }}</td>
             </tr>
             <tr>
              <td><b>{{ __('labels.phone') }}</b></td>
              <td>{{ $invoice->contact->phone }}</td>
              <td><b>{{ __('labels.term') }}</b></td>
              <td>{{ Config::get('constants.terms')[$invoice->term] }} {{ $invoice->term == 'manual' ? '('.$invoice->manual_days.' '.__('labels.days').')' : '' }} </td>
            </tr>
            @endforeach
            </tbody>
           </table>
         </div>
         <div class="default-table add-invoice-table">
           <div class="list-table-custom">
             <div class="generate-invoice">
              <table class="table table-striped">
                <thead>
                 <tr>
                  <th>{{ __('labels.item') }}</th>
                  <th>{{ __('labels.reference') }}</th>
                  <th>{{ __('labels.description') }}</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($invoice->items as $item)
                 <tr>
                  <td><a href="{{route('inventories.show', $item->inventory)}}">{{$item->inventory->name}}</a></td>
                  <td>{{$item->reference}}</td>
                  <td>{{showIfAvailable($item->inventory->description)}}</td>
                 </tr>
                  @endforeach
                </tbody>
               </table>
            </div>
           </div>
         </div>
         <div class="terms-conditions-form">
             <div class="row">
                <div class="form-group col-sm-4">
                 <label for="tac">{{ __('labels.terms_and_conditions') }}</label>
                 <textarea class="form-control" name="tac">{{ old('tac', null) }}</textarea>
                </div>
                <div class="form-group col-sm-4">
                 <label for="notes col-sm-12">{{ __('labels.notes') }}</label>
                 <textarea class="form-control" name="notes" id="notes">{{ $invoice->notes }}</textarea>
                </div>
                <div class="form-group col-sm-4">
                 <label for="res_text col-sm-12">{{ __('labels.resolution_text') }}</label>
                 <textarea class="form-control" name="res_text" id="res_text">{{ old('res_text', null) }}</textarea>
                </div>
              </div>
             </div>
           </div>
         <div class="clearfix"></div>
         <div class="modal fade" id="ShippingEmailModal" tabindex="-1" role="dialog" aria-labelledby="shippingEmailModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
           <form id="send-shipping-mail" action="{{ route('invoices.mail', ['invoice' => $invoice, 'view' => $viewType]) }}" method="POST">
            @csrf
            <input type="hidden" name="template_number" value="15">
           <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="shippingEmailModalLabel">{{ __('labels.send_invoice_to_emails') }}</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
                 <span aria-hidden="true">&times;</span>
                 </button>
            </div>
            <div class="modal-body">
             <input type="text" class="form-control" required="required" name="emails" placeholder="{{ __('labels.separating_addresses_by_comma') }}"
                 value="{{ $invoice->contact->email ? $invoice->contact->email.',': null }}">
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary"
                 data-dismiss="modal">{{ __('labels.cancel') }}</button>
            <button type="submit" class="btn btn-primary">{{ __('labels.send') }}</button>
           </div>
          </div>
         </form>
        </div>
       </div>
       <div style="display:none">
       <div class="print-invoice-shipping">
       </div>
       </div>
@endsection