routes/web.php
		Route::get('invoices/{invoice}/pdf', 'InvoiceController@pdf')->name('invoices.pdf');
		Route::get('invoices/{invoice}/print', 'InvoiceController@print')->name('invoices.print');
		Route::get('invoices/{invoice}/print/template/{template_no}/{view}', 'InvoiceController@printWithTemplate');
		Route::post('invoices/{invoice}/mail', 'InvoiceController@mail')->name('invoices.mail');
		Route::get('invoices/{invoice}/makeProduction', 'InvoiceController@makeProductionOrder')->name('invoices.makeProduction');
		Route::get('invoices/{invoice}/clone', 'InvoiceController@clone')->name('invoices.clone');
		Route::get('invoices/{invoice}/recurring', 'InvoiceController@recurring')->name('invoices.recurring');
		Route::post('invoices/{invoice}/makeRecurring', 'InvoiceController@convertInvoice')->name('invoices.makeRecurring');
		Route::resource('shipping', 'ShippingController');
	});
	Route::resource('restaurant-table', 'TableController');
	//Route::group(['middleware' => ['redirect_for_accountrecivable']], function () {
		Route::get('receivable','AccountReceivableController@index')->name('receivable.index');
		Route::get('receivable/create','AccountReceivableController@create')->name('receivable.create');
		Route::post('receivable','AccountReceivableController@store')->name('receivable.store');
		Route::get('delete/{id}','AccountReceivableController@destroy')->name('receivable.delete');
		Route::get('pdf/{id}','AccountReceivableController@downloadpdf')->name('receivable.pdf');
		Route::get('view/{id}','AccountReceivableController@show')->name('receivable.show');
		

		//});



	Route::group(['middleware' => ['redirect_for_transactions']], function () {
		Route::get('transactions', function() {
			return redirect()->route('transactions.index', ['type' => 'in']);
		});
		
		Route::get('transactions/{type}', 'TransactionController@index')->where('type', 'in|out|recurring')->name('transactions.index');
		Route::get('transactions/create/{type}', 'TransactionController@create')->where('type', 'in|out|recurring')->name('transactions.create');
		Route::post('transactions/{type}', 'TransactionController@store')->where('type', 'in|out|recurring')->name('transactions.store');

		Route::resource('transactions', 'TransactionController')->except([
		    'create', 'store', 'index'
		]);
		Route::get('transactions/{transaction}/print', 'TransactionController@print')->name('transactions.print');
	});

	Route::group(['middleware' => ['permission:manage contacts']], function () {
		Route::resource('clients', 'ClientController');
		Route::resource('suppliers', 'SupplierController');
	});
		
	Route::group(['middleware' => ['permission:manage inventories']], function () {
		Route::resource('taxes', 'TaxController')->except([
		    'show'
		]);
		Route::get('taxes/{tax}', function() {
			return redirect()->route('taxes.index');
		});
		Route::resource('item-categories', 'ItemCategoryController')->except([
		    'show'
		]);
		Route::get('item-categories/{item_category}', function() {
			return redirect()->route('item-categories.index');
		});
		Route::any('inventories/search', 'InventoryController@search')->name('inventories.search')->withoutMiddleware(['permission:manage inventories']);
		Route::resource('inventories', 'InventoryController');
		Route::resource('inventory-adjustments', 'InventoryAdjustmentController');
		Route::resource('units', 'UnitController');
	});

	Route::middleware([AdminOrSuperAdmin::class])->group(function () {
		Route::get('/settings/user', 'UserController@edit')->name('users.edit');
		Route::post('/settings/user', 'UserController@update')->name('users.update');
		Route::get('/settings/company', 'UserController@company')->name('company.edit');
		Route::post('/settings/company', 'UserController@companyUpdate')->name('company.update');
		Route::resource('employees', 'EmployeeController');
		Route::resource('departments', 'DepartmentController');
		Route::resource('designations', 'DesignationController');
		Route::resource('insurance-brands', 'InsuranceBrandController');
		Route::resource('leave-types', 'LeaveTypeController');
		Route::resource('leave-applications', 'LeaveApplicationController');
		Route::get('leave-reports', 'LeaveReportController@index')->name('leave-reports.index');
		Route::get('summary-report', 'LeaveReportController@summary')->name('summary-report.summary');
		Route::get('my-leave-report', 'LeaveReportController@my_leave_report')->name('my-leave-report.my-leave');
		Route::get('requested-applications', 'LeaveApplicationController@requested_applications')->name('requested-applications.requested');

		Route::resource('benefits', 'BenefitController');
		Route::resource('with-holdings', 'WithHoldingController');
		Route::resource('discounts', 'DiscountController');
		Route::resource('extra-hours', 'ExtraHourController');
		Route::resource('payroll-reports', 'PayrollReportController');

		Route::resource('roles', 'RoleController')->except([
		    'show'
		]);
		Route::get('roles/{role}', function() {
			return redirect()->route('roles.index');
		});

		Route::resource('memberships', 'MembershipController');

		/* Route::resource('leaves', 'LeaveController'); */

		Route::resource('leaves', 'LeaveController', ['parameters' => [
    		'leaves' => 'leave'
		]]);

		Route::post('/paid', 'PayrollReportController@paid')->name('employees.paid');
		Route::resource('history', 'HistoryController');
	});

	Route::prefix('user-management')->middleware([AdminOrSuperAdmin::class])->group(function () {
		 Route::get('users', 'UserManagementController@users')->name('user-management.users');
		Route::resource('users', 'UserManagementController')->except([
		    'index',
		    'show',
		])->names([
		    'create' => 'user-management.users.create',
		    'store' => 'user-management.users.store',
		    'edit' => 'user-management.users.edit',
		    'update' => 'user-management.users.update',
		    'destroy' => 'user-management.users.destroy'
		])->parameters([
		    'users' => 'company_user'
		]); 

		/*Route::resource('roles', 'RoleController')->except([
		    'show'
		])->names([
		    'index' => 'user-management.roles.create',
		    'create' => 'user-management.roles.create',
		    'store' => 'user-management.roles.store',
		    'edit' => 'user-management.roles.edit',
		    'update' => 'user-management.roles.update',
		    'destroy' => 'user-management.roles.destroy'
		]);*/
		

		// Route::get('roles', 'UserManagementController@roles')->name('user-management.roles');
		// Route::match(['get', 'post'], 'roles/create', 'UserManagementController@createRole')->name('user-management.roles.create');
		// Route::get('roles/{role}', 'UserManagementController@editRole')->name('user-management.roles.edit');
		// Route::put('roles/{role}/update', 'UserManagementController@assignPermissionsToRole')->name('user-management.roles.update');
	});

	Route::group(['middleware' => ['permission:manage inventories|manage contacts']], function () {
		Route::get('/import/{resource}', 'ImportController@showForm')->where('resource', 'clients|suppliers|inventories|item-categories|banks')->name('import_resource');
		Route::post('/import/{resource}', 'ImportController@processImport')->where('resource', 'clients|suppliers|inventories|item-categories|banks')->name('import_process');

		Route::get('/export/{resource}', 'ExportController@export')->where('resource', 'clients|suppliers|inventories|item-categories')->name('export_resource');
	});

	Route::prefix('app')->group(function () {
	    Route::post('generate-item-row', 'AppController@generateItemRow');
	    Route::post('generate-concept-row', 'AppController@generateConceptRow');
	    Route::post('contact-invoices-row', 'AppController@getContactInvoicesRows');
	    Route::post('contact-credit-notes', 'AppController@getContactCreditNotes');
	    Route::post('contact-debit-notes', 'AppController@getContactDebitNotes');
	    // Route::post('set-locale', 'AppController@setLocale')->withoutMiddleware(['completed']);
	    Route::get('clear-cache', 'AppController@clearCache');
	    Route::get('coming-soon', 'AppController@comingSoon')->name('coming-soon');
		Route::get('contact-leave-balance', 'AppController@getContactLeaveBalance');
	    Route::post('generate-account-adjustment-row', 'AppController@generateAccountAdjustmentRow');
	    Route::post('generate-depr-item-row', 'AppController@generateDeprItemRow');
	    Route::get('get-depreciation-timeline', 'AppController@getDepreciationTimeline');
	});

	Route::get('generate-invoices-payments', 'AppController@generateInvoicesPayments');
	Route::post('documents/upload-files','DocumentController@uploadFiles');
	Route::post('documents/delete-file','DocumentController@deleteFile');
	Route::get('currency-exchange-rates', 'CurrencyExchangeRateController@index')->name('currency-exchange-rates.index');

	Route::resource('fixed-assets', 'FixedAssetController');

	


	Route::prefix('accounting')->group(function () {
		Route::resource('charts', 'UserAccountingHeadController', ['names' => [
		    'index' => 'accounting.charts'
		]])->except([
		    'show'
		]);
		Route::get('charts/generate-control-options/{chart}', 'UserAccountingHeadController@generateControlOptions')->name('accounting.generate-control-options');
		Route::resource('adjustments', 'AccountAdjustmentController')->names([
		    'index' => 'accounting.adjustments.index',
		    'create' => 'accounting.adjustments.create',
		    'store' => 'accounting.adjustments.store',
		    'show' => 'accounting.adjustments.show',
		    'edit' => 'accounting.adjustments.edit',
		    'update' => 'accounting.adjustments.update',
		    'destroy' => 'accounting.adjustments.destroy'
		])->parameters([
		    'adjustments' => 'account_adjustment'
		]);
		Route::get('journals', 'AccountingReportController@journals')->name('accounting.journals');
		Route::get('reports', 'AccountingReportController@index')->name('accounting.reports');

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;
use App\History;

class Unit extends Model
{
    use SoftDeletes;
    use HasTranslations;
    public $timestamps = true;
    public $translatable = ['unit', 'shortcut'];
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'units';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];
    
    public function company()
    {
        return $this->belongsTo('App\Company');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    protected static function booted()
    {
        static::updated(function($unit){
            $updatedata = History::updatedata();
            $unit->histories()->create($updatedata);
        });
        static::deleted(function($unit) {
            $deletedata = History::deletedata();
            $unit->histories()->create($deletedata);
        });
    }
    public function histories()
    {
        return $this->morphMany('App\History', 'record');
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Unit;
use App\Supplier;
use App\Client;
use App\Item;
use App\ConceptItem;
use App\Inventory;
use App\User;
use App\Estimate;
use App\PurchaseOrder;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

use App\Validators\InvoiceValidator;
use App\Mail\InvoiceShared;
use App\Mail\InvoiceCreated;
use App\Events\SaleInvoiceCreatedOrUpdated;
use App\Events\ProfileCompleted;

use DB;
use Auth;
use Config;
use Image;
use PDF;
use Cache;
use File;
use Session;

class UnitController extends Controller
{
    public function __construct()
    {
        // $this->authorizeResource(Unit::class, 'units');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $type = self::SALE)
    {
        $user = $request->user();
        $units = $user->company->units;
        if ($request->wantsJson() || $request->ajax()) {
            $jsonCollection = collect();
            $units->each(function ($item, $key) use ($jsonCollection) {
                $jsonCollection->push([
                    'id' => $item->id,
                    'unit' => $item->unit,
                    'shortcut' => $item->shortcut
                ]);
            });
            return response()->json(['data' => $jsonCollection]);
        }
        return view('unit.index', compact('units', 'type'));
    }

        /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = Auth::user();
        return view('unit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            $input = $request->all();
            $user = $request->user();

            // $data = [
            //     'unit' => $input['unit'],
            //     'shortcut' => $input['shortcut'],
            //     'user_id' => $user->id,
            //     'company_id' => $user->company_id
            // ];

            // $units = new Unit;

            // $unit = $units->create($data);
            $unit = new Unit(['company_id' => $user->company->id,
                        'user_id' => $user->id,
                        ]);
            $unit->setTranslation('unit', 'en', $input['unit'])->setTranslation('unit', 'es', $input['unit']);
            $unit->setTranslation('shortcut', 'en', $input['shortcut'])->setTranslation('shortcut', 'es', $input['shortcut']);
            // $unit = new Unit($unitData);
            $unit->save();
            DB::commit();

            $request->session()->flash('success', trans('messages.unit_created'));
            return redirect()->route('units.index');

        } catch (\Exception $e) {
            DB::rollback();
            $request->session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

     /**
     * Display the specified resource.
     *
     * @param  \App\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function show(Unit $unit)
    {
        return view('unit.show', compact('unit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $user = Auth::user();
        
        // $taxes = $user->company->taxes;

        return view('unit.edit', compact('unit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Unit  $inventory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unit $unit)
    {
        try {
            DB::beginTransaction();
            $input = $request->all();
            $data = [
                'unit' => $input['unit'],
                'shortcut' => $input['shortcut'],
            ];
            $unit->setTranslation('unit', 'en', $input['unit'])->setTranslation('unit', 'es', $input['unit']);
            $unit->setTranslation('shortcut', 'en', $input['shortcut'])->setTranslation('shortcut', 'es', $input['shortcut']);
            // $unit = new Unit($unitData);
            $unit->update();

            DB::commit();

            $request->session()->flash('success', trans('messages.unit_update'));
            return redirect()->route('units.index');

        } catch (\Exception $e) {
            DB::rollback();
            $request->session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Unit $unit)
    {
        try {
            if ($unit) {
                $unit->delete();
                $request->session()->flash('success', trans('messages.unit_deleted'));
            } else {
                $request->session()->flash('error', trans('messages.delete_prohibited'));
            }
            return redirect()->route('units.index');
        } catch (\Exception $e) {
            $request->session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

}

resources/views/unit/create.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.create').' '.trans('labels.measurement_unit'))

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.new_label').' '.__('labels.measurement_unit') }}</h2>
        <form method="POST" action="{{ route('units.store') }}" id="add-edit-unit-form">
            @csrf
            <div class="default-form add-new-contact-form">
                <div class="generate-invoice">
                    <div class="add-form row">
                        <div class="form-group col-sm-6">
                            <label for="unit">{{ __('labels.measurement_unit') }} <span>*</span></label>
                            <input class="form-control" type="text" name="unit" placeholder="{{ __('labels.measurement_unit') }}" required value="{{ old('unit') }}" autocomplete="off" />
                            @error('unit')
                                <span class="error" role="alert">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="shortcut">{{ __('labels.symbol') }} <span>*</span></label>
                            <input class="form-control" type="text" name="shortcut" placeholder="{{ __('labels.symbol') }}" required value="{{ old('shortcut') }}" autocomplete="off" />
                            @error('shortcut')
                                <span class="error" role="alert">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments-section">
                    <div class="form-group popup-btns">
                        <a href="{{ route('units.index') }}"><button type="button" name="cancel" class="btn-custom cancel-btn">{{ __('labels.cancel') }}</button></a>
                        <button type="submit" name="submit" class="btn-custom">{{ __('labels.save') }}</button>
                    </div>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
</div>
@endsection

resources/views/unit/edit.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.modify').' '.trans('labels.measurement_unit'))

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.modify').' '.__('labels.measurement_unit') }}</h2>
        {{ Form::open(array('method'=>'PUT','route' => ['units.update', $unit], 'id' => 'add-edit-unit-form')) }}
            <div class="default-form add-new-contact-form">
                <div class="generate-invoice">
                    <div class="add-form row">
                        <div class="form-group col-sm-6">
                            <label for="unit">{{ __('labels.measurement_unit') }} <span>*</span></label>
                            <input class="form-control" type="text" name="unit" placeholder="{{ __('labels.measurement_unit') }}" required value="{{ old('unit', $unit->unit) }}" autocomplete="off" />
                            @error('unit')
                                <span class="error" role="alert">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="shortcut">{{ __('labels.symbol') }} <span>*</span></label>
                            <input class="form-control" type="text" name="shortcut" placeholder="{{ __('labels.symbol') }}" required value="{{ old('shortcut', $unit->shortcut) }}" autocomplete="off" />
                            @error('shortcut')
                                <span class="error" role="alert">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments-section">
                    <div class="form-group popup-btns">
                        <a href="{{ route('units.index') }}"><button type="button" name="cancel" class="btn-custom cancel-btn">{{ __('labels.cancel') }}</button></a>
                        <button type="submit" name="submit" class="btn-custom">{{ __('labels.save') }}</button>
                    </div>
            </div>
    </div>
</div>
<div class="clearfix"></div>
</div>
@endsection

resources/views/unit/index.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.measurement_unit'))

@section('content')
<div class="dashboard-right cust-dashboard-md-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.measurement_unit') }}</h2>
        <div class="custom-tooltip"><span class="help-icon"><i class="fa fa-question-circle" aria-hidden="true"></i>
            </span>
            <span class="tooltiptext">{{ __('labels.if_you_need_help_creating_an').' '.__('labels.measurement_unit') }}.</span>
        </div>
        <div class="invoice-btns invoice-btns-position">
            {{-- <a href="{{ route('import_resource', ['resource' => 'units']) }}" class="btn-custom outline-btn"><i
                    class="fa fa-upload" aria-hidden="true"></i> {{ __('labels.import_from_excel') }}</a>
            <a href="{{ route('export_resource', ['resource' => 'units']) }}" class="btn-custom outline-btn"><i
                    class="fa fa-download" aria-hidden="true"></i> {{ __('labels.export') }}</a> --}}
            <a href="{{ route('units.create') }}" class="btn-custom" id="create-new-unit-btn"><i
                    class="fa fa-plus" aria-hidden="true"></i>
                {{ __('labels.new').' '.__('labels.measurement_unit') }}</a>
        </div>
        <div class="tabs-custom">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="list-table-custom  products-table">
                        <table class="table table-striped" id="unit-list-table">
                            <thead>
                                <tr>
                                    <th>{{ __('labels.measurement_unit') }}</th>
                                    <th>{{ __('labels.symbol') }}</th>
                                    <th>{{ __('labels.actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($units as $unit)
                                <tr>
                                    <td>{{ $unit->unit }}</td>
                                    <td>{{ $unit->shortcut }}</td>
                                    <td class="to-show">
                                        <div class="inner-to-show">
                                            <i class="fa fa-sort-desc action-btn" class="dropdown-toggle"
                                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                                            <div class="dropdown-menu">
                                                <ul>
                                                    <li><a
                                                            href="{{route('units.show', $unit)}}">{{ __('labels.view') }}</a>
                                                    </li>
                                                    <li><a
                                                            href="{{route('units.edit', $unit)}}">{{ __('labels.edit') }}</a>
                                                    </li>
                                                    <li><a class="delete_resource"
                                                        data-resource="{{ 'destroy-inventory-form-' . $unit->id }}"
                                                        href="{{route('units.destroy', $unit)}}">{{ __('labels.delete') }}</a>
                                                </li>
                                                {{ Form::open(array('method'=>'DELETE','route' => ['units.destroy', $unit], 'id' => "destroy-inventory-form-{$unit->id}", 'style' => 'display: none')) }}
                                                {!! Form::close() !!}
                                                </ul>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @empty
                                @endforelse
                            </tbody>
                            <tfoot>
                                <tr>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection

<div class="welcome-popup-outer" id="inventory-type-container" style="display: none;">
    <!--step1-->
    <form id="inventory-type-form" onsubmit="return false;">
        <div class="steps-form step1">
            <div class="welcome-popup-bottom">
                <div class="welcome-msg text-center">
                    <h2>{{ __('labels.select_inventory_type') }}</h2>
                    <p></p>
                </div>
                <div class="custom-radio-container">
                    <div class="custom-radio">
                        <input type="radio" name="inventory_type" value="inventory" id="inventory">
                        <label for="inventory">
                            <img src="{{ asset('/images/f-label-1.png') }}">
                            {{ __('labels.inventory') }}
                        </label>
                    </div>
                    <div class="custom-radio">
                        <input type="radio" name="inventory_type" value="services" id="services">
                        <label for="services">
                            <img src="{{ asset('/images/f-label-2.png') }}">
                            {{ __('labels.services') }}
                        </label>
                    </div>
                    <div class="custom-radio">
                        <input type="radio" name="inventory_type" value="non-inventory" id="non_inventory">
                        <label for="non_inventory">
                            <img src="{{ asset('/images/f-label-1.png') }}">
                            {{ __('labels.non_inventory') }}
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/unit/show.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.show').' '.trans('labels.measurement_unit'))

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <a class="arrow-back d-block" href="{{ route('units.index') }}">{{ __('labels.back') }}</a>
        <h2>{{ __('labels.measurement_unit').' '.__('labels.details') }}</h2>
        <div class="default-form view-form-detail item-detail-view view-details-product-ser">
            <div class="generate-invoice">
                <div class="add-form row">
                    <div class="col-md-8 view-details-product-cell">
                        <div class="form-outer">
                            <div class="form-group">
                                <label for="tax"><b>{{ __('labels.measurement_unit') }} </b></label>
                                <span class="value-form">{{ $unit->unit }}</span>
                            </div>
                        </div>
                        <div class="form-outer">
                            <div class="form-group">
                                <label for="sale_price"><b>{{ __('labels.symbol') }} </b></label>
                                <span class="value-form">{{ $unit->shortcut }}</span>
                            </div>
                        </div>
                    </div>
            </div>
            </div>

        </div>
    </div>
</div>
</div>
<div class="clearfix"></div>
</div>
@endsection